package com.example.data.utils;

import com.example.domain.model.ErrorType;
import com.example.domain.model.Result;
import kotlinx.coroutines.flow.Flow;
import retrofit2.HttpException;
import java.io.IOException;

@kotlin.Metadata(mv = {1, 9, 0}, k = 2, xi = 48, d1 = {"\u0000\u000e\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0003\n\u0000\u001a\u000e\u0010\u0000\u001a\u00020\u00012\u0006\u0010\u0002\u001a\u00020\u0003\u00a8\u0006\u0004"}, d2 = {"handleError", "Lcom/example/domain/model/Result$Error;", "exception", "", "data_debug"})
public final class FlowUtilsKt {
    
    @org.jetbrains.annotations.NotNull()
    public static final com.example.domain.model.Result.Error handleError(@org.jetbrains.annotations.NotNull()
    java.lang.Throwable exception) {
        return null;
    }
}